version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ..:/code-is-nasdaq-open-now
    networks:
      webnet:
        ipv4_address: 180.10.10.101

  # *****************************
  # php-fpm
  # *****************************
  php_fpm:
    container_name: is-nasdaq-open-now-container-php
    build: build/php-fpm
    ports:
      - 9001:9001
    environment:
      XDEBUG_CONFIG: "remote_host=${ISNASDAQOPENNOW_DEBUG_HOST_IP}"
      PHP_IDE_CONFIG: "serverName=is-nasdaq-open-now-php"
    volumes:
      - ./build/php-fpm/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

      # Map all projects to easy access all available code
      - ..:/code-is-nasdaq-open-now
    networks:
      webnet:
        ipv4_address: 180.10.10.102
        aliases:
          - php-fpm.is-nasdaq-open-now.test

  # *****************************
  # database
  # *****************************
  db:
    container_name: is-nasdaq-open-now-container-mysql
    build: build/db
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql

      # Map all projects to easy access all available code
      - ..:/code-is-nasdaq-open-now
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=is_nasdaq_open_now
    networks:
      webnet:
        ipv4_address: 180.10.10.103
        aliases:
          - db.is-nasdaq-open-now.test

networks:
  webnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 180.10.10.0/24

volumes:
  db-volume:
