name: First workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Hello Codelies!
        run: echo "Hello!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: 😊 More and more
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Done!"

      - name: Install composer dependencies
        # working-directory: ./you/can/run/this/from-any-path
        run: composer install --ignore-platform-reqs

      #- name: Before using Laravel's encrypter, you must set a key option in your config/app.php configuration file
      #  run: php artisan key:generate

      - name: Run the tests
        run: ./vendor/bin/phpunit
